language: ruby
sudo: false
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0-preview1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem update bundler
notifications:
  email:
    - ogataken@gmail.com
